import {routes} from 'navigation';

export const DASHBOARD_ITEMS = [
  {
    listRout: routes.NANDI_SERVICE_LIST,
    formRoute: routes.NANDI_SERVICE_FORM,
    key: 'form_1',
    value: 'nandiService',
    count: 10,
  },
  {
    listRout: routes.LIVESTOCK_LIST,
    formRoute: routes.LIVESTOCK_FORM,
    key: 'form_2',
    value: 'livestock',
    count: 15,
  },
  {
    listRout: routes.DEATH_LIST,
    formRoute: routes.DEATH_FORM,
    key: 'form_3',
    value: 'death',
    count: 25,
  },
  {
    listRout: routes.BIRTH_LIST,
    formRoute: routes.BIRTH_FORM,
    key: 'form_4',
    value: 'birth',
    count: 10,
  },
  {
    listRout: routes.MILK_PRODUCTION_LIST,
    formRoute: routes.MILK_PRODUCTION_FORM,
    key: 'form_5',
    value: 'milkProduction',
    count: 20,
  },
  {
    listRout: routes.FALYA_RECORD_LIST,
    formRoute: routes.FALYA_RECORD_FORM,
    key: 'form_6',
    value: 'falyaRecord',
    count: 18,
  },
  {
    listRout: routes.ILLNESS_RECORD_LIST,
    formRoute: routes.ILLNESS_RECORD_FORM,
    key: 'form_7',
    value: 'illnessRecord',
    count: 12,
  },
  {
    listRout: routes.WORM_VACCINATION_LIST,
    formRoute: routes.WORM_VACCINATION_FORM,
    key: 'form_8',
    value: 'wormVaccination',
    count: 16,
  },
  {
    listRout: routes.LABORATORY_LIST,
    formRoute: routes.LABORATORY_FORM,
    key: 'form_9',
    value: 'laboratory',
    count: 22,
  },
  {
    listRout: routes.VACCINATION_LIST,
    formRoute: routes.VACCINATION_FORM,
    key: 'form_10',
    value: 'vaccination',
    count: 19,
  },
  {
    listRout: routes.BREEDING_LIST,
    formRoute: routes.BREEDING_FORM,
    key: 'form_11',
    value: 'breeding',
    count: 14,
  },
];
