export const routes = {
  // Auth screens
  WELCOME: 'WELCOME',
  LOGIN: 'LOGIN',
  VERIFY_OTP: 'VERIFY_OTP',

  // Main screens
  MAIN_BOTTOM_TAB: 'MAIN_BOTTOM_TAB',
  MAIN_HOME: 'Home',
  MAIN_WEATHER: 'Weather',
  MAIN_SETTINGS: 'Settings',
  MAIN_TEST: 'Test',

  // TABLES
  NANDI_SERVICE_LIST: 'NANDI_SERVICE_LIST',
  LIVESTOCK_LIST: 'LIVESTOCK_LIST',
  DEATH_LIST: 'DEATH_LIST',
  BIRTH_LIST: 'BIRTH_LIST',
  MILK_PRODUCTION_LIST: 'MILK_PRODUCTION_LIST',
  FALYA_RECORD_LIST: 'FALYA_RECORD_LIST',
  ILLNESS_RECORD_LIST: 'ILLNESS_RECORD_LIST',
  WORM_VACCINATION_LIST: 'WORM_VACCINATION_LIST',
  LABORATORY_LIST: 'LABORATORY_LIST',
  VACCINATION_LIST: 'VACCINATION_LIST',
  BREEDING_LIST: 'BREEDING_LIST',

  // FORMS
  NANDI_SERVICE_FORM: 'NANDI_SERVICE_FORM',
  LIVESTOCK_FORM: 'LIVESTOCK_FORM',
  DEATH_FORM: 'DEATH_FORM',
  BIRTH_FORM: 'BIRTH_FORM',
  MILK_PRODUCTION_FORM: 'MILK_PRODUCTION_FORM',
  FALYA_RECORD_FORM: 'FALYA_RECORD_FORM',
  ILLNESS_RECORD_FORM: 'ILLNESS_RECORD_FORM',
  WORM_VACCINATION_FORM: 'WORM_VACCINATION_FORM',
  LABORATORY_FORM: 'LABORATORY_FORM',
  VACCINATION_FORM: 'VACCINATION_FORM',
  BREEDING_FORM: 'BREEDING_FORM',

  // Other navigation
  ENTER_LOCATION: 'ENTER_LOCATION',
  LOST_CONNECTION: 'LOST_CONNECTION',
  WEATHER_TRACKING: 'WEATHER_TRACKING',
  CHAT: 'CHAT',
  CHAT_LIST: 'CHAT_LIST',
  ADD_TODO: 'ADD_TODO',
  TODO: 'TODO',
  LANGUAGE_LIST: 'LANGUAGE_LIST',
  SHARE: 'SHARE',
};
